spring:
  application:
    name: spring-elasticsearch-sample
  data:
    elasticsearch:
      cluster-names: docker-cluster
      #      cluster-node: 192.168.99.100:9300
      cluster-node: localhost:9300

  elasticsearch:
    rest:
      #      uris: http://192.168.99.100:9200
      uris: localhost:9200
      connection-timeout: 1s
      read-timeout: 1m
      password: elastic
      username: changeme

initial-import:
  enabled: false

